### ISSUE TITLE
[Footer enhancement] Added footer details

### ISSUE THREAD

**Issue by SamantaCasal** [XLabs/wormscan-ui#234]
Design change

Footer should add "we're hiring" link, should lead to the xlabs careers page
Terms of Service link
Bug bounty link
Contact us form via email

Add arrow to link back to top

---

@erikXLXYZ

This will need work on:

- Product:
  - Provide the relevant URLs

- UI
- Front-end

**Comment by Gpluv** [comment]
This task is complemented by ticket 234.
The design: [Here](https://www.figma.com/file/kVuUyVjFFcRP55xHxHoKtH/WormholeScan?type=design&node-id=3876-16400&mode=design&t=K6iU4Kgqbm05wC8S-4)

Acceptance Criteria:

1. The **Built by xlabs** should link to the xlabs.xyz website and should have a hoverlink underline with the same secodary 900 color.
2. The We're hiring label has a 12px font, it would be the only place with that font.
3. Carrers points to the link: https://boards.greenhouse.io/xlabs
4. The button: Back to Top, sends you to the top of the site, when hovering use the color: secodary 900
5. Contact Us: same link as Join discord
6. Bug Bounty (it won't be available yet but it will be there)
7. For the mobile version, due to the new elements, I have designed the space in two columns for navigation.

**Comment by SamantaCasal** [comment]
I close this ticket because the comments are at https://github.com/orgs/XLabs/projects/1/views/1?pane=issue&itemId=33704527
