### ISSUE TITLE
[Bug] Does not show information for Generic Relayer transaction

### ISSUE THREAD

**Issue by SamantaCasal** [XLabs/wormscan-ui#407]
**Environment:**macOs Sonoma 14.0   Chrome Version 117.0.5938.149 (Official Build) (arm64)

**Tested from:**
Fronted version: v1.1.6
[PROD ](https://wormholescan.io/#/)/ [STG](https://xlabs.github.io/wormscan-ui/#/)

**Current behavior:**
When entering the txHash transaction detail 0x8d875ab73f4e740a1ca352674937558670f7e053e6c82a723276d0a68e7d2f39. You see the message: "This is either not an Automatic Relayer VAA or something's wrong with it", however in the console we can see the transaction information.

**Expected behavior:**
The corresponding information is shown in the transaction details

**Steps to reproduce**
1. Go to https://xlabs.github.io/wormscan-ui/#/tx/0x8d875ab73f4e740a1ca352674937558670f7e053e6c82a723276d0a68e7d2f39
2. Open Console Open the browser console
3. Observe the result
4. In the console, click on the network
5. Click on the transaction endpoint
6. Observe the result 

**Evidence:**

![Image](https://github.com/XLabs/wormscan-ui/assets/69044575/c6c1ac6e-21ad-4694-9386-50147cd2eb42)

![Image](https://github.com/XLabs/wormscan-ui/assets/69044575/53e7caea-f444-48fd-b987-559789d43314)

**Comment by valentinoConti** [comment]
I was investigating on this and the cause for this problem seems to be that the transaction linked is a **redelivery instruction** and not a **delivery instruction**

I tried to see if there's some workaround to at least show some of the information with our same design/code but the information that comes for this cases are completely different than what we expect, see:

---
REGULAR GENERIC RELAYER RESPONSE (DELIVERY)

![Image](https://github.com/XLabs/wormscan-ui/assets/41705567/c0fc0467-aa5e-4779-9d63-e47f254a2848)

---
REDELIVERY RESPONSE

![Image](https://github.com/XLabs/wormscan-ui/assets/41705567/9c907eb6-cd94-4acd-8e48-116dc0db7992)

---
So my conclusion for this ticket is: **This is not a bug. The solution for this its adding a new feature that we don't support yet**.

In case that we want to do that, we'll need to ask the relayer team what info would be useful to show in cases of a redelivery and how the response should look like.

The backend team is already working on making the generic-relayer endpoint be available on WHSCAN API, so probably if we decide to tackle this case, we should do it together (front + back + relayer) to analyze the best solution.
